version: "0.2"
language: en-US
words:
  - apimachinery
  - corev
  - apiserver
  - configmap
  - databroker
  - deepcopy
  - envtest
  - filemgr
  - hostnames
  - mockgen
  - oidc
  - otel
  - otlp
  - pomerium
  - protobuf
  - protojson
  - readyz
  - rego
  - sharedkey
  - sslcert
  - sslkey
  - sslrootcert
  - uifs
  - unmarshaled
  - upsert
languageSettings:
  - languageId: go
    allowCompoundWords: false
    ignoreRegExpList:
      - Urls
      - Base64
      - "/kubebuilder:.*/"
      - "/nolint:.*/"
      - "/go:.*/"
    includeRegExpList:
      - CStyleComment
