apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium-databroker
spec:
  template:
    spec:
      containers:
        - name: pomerium
          image: pomerium/ingress-controller:v0.32.0
          imagePullPolicy: IfNotPresent
