apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base.yaml
patches:
- path: args.yaml
- path: image.yaml
- path: ports.yaml
- path: resources.yaml
- path: no-root.yaml
- path: readonly-root-fs.yaml
- path: healthcheck.yaml
