---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: settings.ingress.pomerium.io
spec:
  group: ingress.pomerium.io
  names:
    kind: Settings
    listKind: SettingsList
    plural: settings
    singular: settings
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Settings is the Schema for the settings API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SettingsSpec defines the desired state of Settings
            type: object
          status:
            description: SettingsStatus defines the observed state of Settings
            properties:
              routes:
                additionalProperties:
<<<<<<< HEAD
                  description: RouteStatus reconciliation status between Ingress spec
                    and Pomerium state
                  properties:
                    error:
=======
                  description: RouteStatus
                  properties:
                    errors:
>>>>>>> 66086a7 (add settings CRD and basic status)
                      description: Error is reason most recent reconciliation failed
                        for the route
                      type: string
                    reconciled:
                      description: Reconciled is true if Ingress resource was fully
                        synced with pomerium state
                      type: boolean
                    ts:
                      description: LastReconciled timestamp indicates when the ingress
                        resource was last synced with pomerium
                      format: date-time
                      type: string
                  required:
                  - reconciled
                  type: object
                type: object
            required:
            - routes
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
